# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Upsame
subtitle: Upsame, the Future !
name: 遇见·未来 
email: upsame@outlook.com
description: 本站是Upsame的技术分享博客。内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: Upsame,5 Generation,Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,生活故事,架构,大数据,一线,FastDFS,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.ico 

repository: upsame/upsame.github.io
github_url: https://github.com/upsame
url:  http://www.upsame.com
enforce_ssl:  upsame.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
  -
    href: http://kdyun.upsame.com/index.php?share/folder&user=103&sid=KGhVeZaU
    label: 可道云
    target: _blank
    
  -
    href: /linux.html
    label: Linux  
    target: _self

  -
    href: /it.html
    label: IT
    target: _self

  -
    href: /mathmodel.html
    label: MathModel
    target: _self   

  -
    href: /fpga.html
    label: FPGA
    target: _self

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /python.html
    label: Python  
    target: _self
    subnav:

      # -
        # subHref: /spring-boot.html
        # subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud

  -
    href: /spring-cloud.html
    label: Computer Net
    target: _self

  -
    
    href: /5G.html
    label: 5G
    target: _self
    subnav:

      -
        subHref: /5G.html
        subLabel: 5G系列文章
        
      -
        subHref: https://www.3gpp.org/
        subLabel: 3GPP 官网
        target: _blank

  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: AboutMe
    target: _self


# labels. my blog key words
labels:

  -
    href: /payment.html
    label: 支付     
    target: _blank

  -
    href: /arch.html
    label: 架构
    target: _blank

  -
    href: /mongodb.html
    label: MongoDB
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /gitchat.html
    label: Chat
    target: _blank

  -
    href: /geektime.html
    label: 极客
    target: _blank


# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 写的是我，说的是你

  -
    href: /fpga.html
    name: FPGA 之路
    describe: 我好难啊！

  -
 #   href: /java.html
    href: /5G.html
    name: 5G 系列文章
    describe: 5 Generation，我们的时代


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: upsame
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: upsame
    repo: upsame.blog-comment
    oauth:
        client_id: cde3a330c0e3231deacc
        client_secret: 5da8e510bead6cbdbbc263b16743ec46fe1eabbd
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: upsame
    repo: upsame.blog-comment
    clientID: cde3a330c0e3231deacc
    clientSecret: 5da8e510bead6cbdbbc263b16743ec46fe1eabbd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
